name: embed_fbcmt
version: 2.0.0
description: An absolute bare-bones web app.
environment: 
  sdk: '>=2.18.6 <3.0.0'
dependencies: 
  js: any
dev_dependencies: 
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
